### ISSUE TITLE
'Specify Rails release migration was written for' error

### ISSUE THREAD

**Issue by ryanwevans** [learn-co-curriculum/mechanics-of-migrations#44]
Hello there,
When running 'rake db:migrate' in terminal, the command is run, but with this error:

DEPRECATION WARNING: Directly inheriting from ActiveRecord::Migration is deprecated. Please specify the Rails release the migration was written for:

  class AddFavoriteFoodToArtists < ActiveRecord::Migration[4.2]

I found when googling this error that sometimes a default in a migration can change between Rails releases, so Active Record wants to know in which version the migrations were generated.  Don't know if you would want to call that out in the lesson?  But it's also good for the learner to find what that error means (like I did) :)

Thanks and have a great day,
Ryan

**Comment by sgharms** [comment]
I love your attitude on this! Yes, depending on how your local environment is configured, you might use a more recent version such that you should provide this extra definition. It will vary between systems, but it's a great thing to note! It's hard to predict how local installs will vary, but in our controlled environment (the new Learn IDE sandbox) this shouldn't be an issue. I'm closing because I can't take action on it, but I like your thoughts!
