### ISSUE TITLE
gems not up to date

### ISSUE THREAD

**Issue by tan-nate** [learn-co-curriculum/mechanics-of-migrations#59]
needed to do `class CreateArtists < ActiveRecord::Migration[4.2]` instead of `class CreateArtists < ActiveRecord::Migration` otherwise error

**Comment by maxwellbenton** [comment]
Hi @tan-nate,

Thank you opening this issue and providing feedback. We've updated this lesson's readme to include messaging about migration syntax, included some information about the error you are referring to and how to avoid it, and believe this issue is resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
