### ISSUE TITLE
article.rb missing

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/mechanics-of-migrations#71]
the readme shows this file as existing but it's not here
that intentional?

**Comment by maxwellbenton** [comment]
Hey @jd2rogers2,

No - at some point in the past, `artist.rb` was deleted. The file was added back in a few months ago but it turns out the v-000 lesson copy on learn-co-students hadn't received any recent updates. I've updated the v-000 lesson directly so it is now up to date with the learn-co-curriculum version. It should also start receiving updates again, now that it is aligned

Thank you for spotting this!
